image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-store-microservice:
  stage: build
  script:
    gradle store-microservice:assemble store-microservice:testClasses

checkStyle-store-microservice:
  stage: staticAnalysis
  script:
    gradle store-microservice:checkstyleMain store-microservice:checkStyleTest
  allow_failure: true


PMD-store-microservice:
  stage: staticAnalysis
  script:
    gradle store-microservice:pmdMain
  allow_failure: true

test-store-microservice:
  stage: test
  script:
    - gradle store-microservice:test store-microservice:jacocoTestReport
    - cat store-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
